---
kind: "operation"
client: "atomist 1.2"
generator:
  name: "NewHandlersProject"
  group: "atomist"
  artifact: "handlers"
  version: "0.5.0"
  origin:
    repo: "git@github.com:atomist/handlers.git"
    branch: "master"
    sha: "c5e6729*"
  parameters:
    - "project_name": "rug-test-10"
    - "group_id": "mygroup"
    - "version": "0.1.0"

---
kind: "operation"
client: "atomist-bot"
executor:
  name: "EnableTravisForRugArchive"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.12.0"
  origin:
    repo: "https://github.com/atomist-rugs/travis-editors.git"
    branch: "678d3e9ccbf3b22079e7551530d9142d3bfdd364"
    sha: "678d3e9"
  parameters:
    - "github_token": "d**************************************0"
    - "maven_user": "t***************y"
    - "maven_token": "z**************7"
    - "owner": "atomisthqa"
    - "repo": "rug-test-10"
    - "org": ".org"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"

